version: "3"
services:
    api:
        restart: unless-stopped
        build:
          context: .
        environment:
            - ConnectionStrings:Carpool=Server=db,1433;Database=160287;User=sa;Password=MasterCoolOkPw52;
        ports:
            - "50552:50552"
        depends_on:
            - db
        links:
            - db
        networks:
            - mynet

    db:
        restart: unless-stopped
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        environment:
            SA_PASSWORD: "MasterCoolOkPw52"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
        ports:
            - 1403:1433
        networks:
            - mynet
networks:
  mynet:
    driver: bridge